//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2014-01-27 by the VDM++ to JAVA Code Generator
// (v9.0.3 - Fri 13-Dec-2013 09:24:01 +0900)
//
// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:/Users/HOMMA/Google ?.

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Record;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class LightVal {

// ***** VDMTOOLS START Name=targLightVal KEEP=NO
  private Number targLightVal = null;
// ***** VDMTOOLS END Name=targLightVal

// ***** VDMTOOLS START Name=lightValRange KEEP=NO
  private LightValRange lightValRange = null;
// ***** VDMTOOLS END Name=lightValRange

// ***** VDMTOOLS START Name=lightValEncoder KEEP=NO
  private LightValEncoder lightValEncoder = null;
// ***** VDMTOOLS END Name=lightValEncoder

// ***** VDMTOOLS START Name=lightValListener KEEP=NO
  private LightValListener lightValListener = null;
// ***** VDMTOOLS END Name=lightValListener

// ***** VDMTOOLS START Name=MAX_LIGHT_VAL KEEP=NO
  public static final Number MAX_LIGHT_VAL = new Integer(1023);
// ***** VDMTOOLS END Name=MAX_LIGHT_VAL


// ***** VDMTOOLS START Name=vdm_init_LightVal KEEP=NO
  private void vdm_init_LightVal () {}
// ***** VDMTOOLS END Name=vdm_init_LightVal


// ***** VDMTOOLS START Name=LightVal KEEP=NO
  public LightVal () /*throws CGException*/ {
    vdm_init_LightVal();
  }
// ***** VDMTOOLS END Name=LightVal


// ***** VDMTOOLS START Name=LightVal#1|LightValEncoder KEEP=NO
  public LightVal (final LightValEncoder LVE) /*throws CGException*/ {
    vdm_init_LightVal();
    lightValEncoder = LVE;
  }
// ***** VDMTOOLS END Name=LightVal#1|LightValEncoder


// ***** VDMTOOLS START Name=getLightVal KEEP=NO
  public Number getLightVal () /*throws CGException*/ {
    return lightValEncoder.getLightVal();
  }
// ***** VDMTOOLS END Name=getLightVal


// ***** VDMTOOLS START Name=getTargLightVal KEEP=NO
  public Number getTargLightVal () /*throws CGException*/ {
    return targLightVal;
  }
// ***** VDMTOOLS END Name=getTargLightVal


// ***** VDMTOOLS START Name=setTargLightVal#1|Number KEEP=NO
  public void setTargLightVal (final Number parm) /*throws CGException*/ {
    targLightVal = parm.intValue();
  }
// ***** VDMTOOLS END Name=setTargLightVal#1|Number


// ***** VDMTOOLS START Name=setLightValRange#1|LightValRange KEEP=NO
  public void setLightValRange (final LightValRange LVR) /*throws CGException*/ {
    lightValRange = LVR;
  }
// ***** VDMTOOLS END Name=setLightValRange#1|LightValRange


// ***** VDMTOOLS START Name=setLightValListener#1|LightValListener KEEP=NO
  public void setLightValListener (final LightValListener LVL) /*throws CGException*/ {
    lightValListener = LVL;
  }
// ***** VDMTOOLS END Name=setLightValListener#1|LightValListener

}
;
