//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2014-03-11 by the VDM++ to JAVA Code Generator
// (v9.0.3 - Fri 13-Dec-2013 09:24:01 +0900)
//
// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\HOMMA\\Google ?.

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class LightValCtrlTimer {

// ***** VDMTOOLS START Name=vdm_init_LightValCtrlTimer KEEP=NO
  private void vdm_init_LightValCtrlTimer () {}
// ***** VDMTOOLS END Name=vdm_init_LightValCtrlTimer


// ***** VDMTOOLS START Name=LightValCtrlTimer KEEP=NO
  public LightValCtrlTimer () throws CGException {
    vdm_init_LightValCtrlTimer();
  }
// ***** VDMTOOLS END Name=LightValCtrlTimer

}
;
