//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2014-01-27 by the VDM++ to JAVA Code Generator
// (v9.0.3 - Fri 13-Dec-2013 09:24:01 +0900)
//
// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:/Users/HOMMA/Google ?.

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class LightValListener extends Listener {

// ***** VDMTOOLS START Name=lvlState KEEP=NO
  private Boolean lvlState = null;
// ***** VDMTOOLS END Name=lvlState

// ***** VDMTOOLS START Name=child KEEP=NO
  protected external_LightValListener child = new external_LightValListener(this);
// ***** VDMTOOLS END Name=child


// ***** VDMTOOLS START Name=vdm_init_LightValListener KEEP=NO
  private void vdm_init_LightValListener () {}
// ***** VDMTOOLS END Name=vdm_init_LightValListener


// ***** VDMTOOLS START Name=getState KEEP=NO
  public Number getState () /*throws CGException*/ {
    return child.impl_getState();
  }
// ***** VDMTOOLS END Name=getState


// ***** VDMTOOLS START Name=noticeOutOfRange#1|Boolean KEEP=NO
  public void noticeOutOfRange (final Boolean parm) /*throws CGException*/ {
    lvlState = (Boolean)UTIL.clone(parm);
  }
// ***** VDMTOOLS END Name=noticeOutOfRange#1|Boolean


// ***** VDMTOOLS START Name=LightValListener KEEP=NO
  public LightValListener () /*throws CGException*/ {
    vdm_init_LightValListener();
  }
// ***** VDMTOOLS END Name=LightValListener

}
;
