//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2014-03-10 by the VDM++ to JAVA Code Generator
// (v9.0.3 - Fri 13-Dec-2013 09:24:01 +0900)
//
// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\HOMMA\\Google ?.

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class LightValEncoderStub implements LightValEncoder {

// ***** VDMTOOLS START Name=brightness KEEP=NO
  private Number brightness = null;
// ***** VDMTOOLS END Name=brightness


// ***** VDMTOOLS START Name=vdm_init_LightValEncoderStub KEEP=NO
  private void vdm_init_LightValEncoderStub () {
    brightness = new Integer(0);
  }
// ***** VDMTOOLS END Name=vdm_init_LightValEncoderStub


// ***** VDMTOOLS START Name=getLightVal KEEP=NO
  public Number getLightVal () /*throws CGException*/ {
    return brightness;
  }
// ***** VDMTOOLS END Name=getLightVal


// ***** VDMTOOLS START Name=LightValEncoderStub KEEP=NO
  public LightValEncoderStub () throws CGException {
    vdm_init_LightValEncoderStub();
  }
// ***** VDMTOOLS END Name=LightValEncoderStub

}
;
