//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2014-01-27 by the VDM++ to JAVA Code Generator
// (v9.0.3 - Fri 13-Dec-2013 09:24:01 +0900)
//
// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:/Users/HOMMA/Google ?.

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class Listener {

// ***** VDMTOOLS START Name=vdm_init_Listener KEEP=NO
  private void vdm_init_Listener () {}
// ***** VDMTOOLS END Name=vdm_init_Listener


// ***** VDMTOOLS START Name=Listener KEEP=NO
  public Listener () /*throws CGException*/ {
    vdm_init_Listener();
  }
// ***** VDMTOOLS END Name=Listener

}
;
