//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2014-01-27 by the VDM++ to JAVA Code Generator
// (v9.0.3 - Fri 13-Dec-2013 09:24:01 +0900)
//
// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:/Users/HOMMA/Google ?.

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class MotorEncoder {

// ***** VDMTOOLS START Name=API KEEP=NO
//  private ecrobot_interface API = null;
//// ***** VDMTOOLS END Name=API

// ***** VDMTOOLS START Name=revL KEEP=NO
  private Number revL = null;
// ***** VDMTOOLS END Name=revL

// ***** VDMTOOLS START Name=revR KEEP=NO
  private Number revR = null;
// ***** VDMTOOLS END Name=revR


// ***** VDMTOOLS START Name=vdm_init_MotorEncoder KEEP=NO
  private void vdm_init_MotorEncoder () {}
// ***** VDMTOOLS END Name=vdm_init_MotorEncoder


// ***** VDMTOOLS START Name=getLCount KEEP=NO
  public Number getLCount () throws CGException {
    return revL;
  }
// ***** VDMTOOLS END Name=getLCount


// ***** VDMTOOLS START Name=getRCount KEEP=NO
  public Number getRCount () throws CGException {
    return revR;
  }
// ***** VDMTOOLS END Name=getRCount


// ***** VDMTOOLS START Name=MotorEncoder KEEP=NO
  public MotorEncoder () throws CGException {
    vdm_init_MotorEncoder();
  }
// ***** VDMTOOLS END Name=MotorEncoder

}
;
