//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2014-01-27 by the VDM++ to JAVA Code Generator
// (v9.0.3 - Fri 13-Dec-2013 09:24:01 +0900)
//
// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:/Users/HOMMA/Google ?.

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.Record;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class PIDLightValCtrl {

// ***** VDMTOOLS START Name=PIDParm KEEP=NO
  private PIDLVCParm PIDParm = null;
// ***** VDMTOOLS END Name=PIDParm

// ***** VDMTOOLS START Name=bfDeviation KEEP=NO
  private Number bfDeviation = null;
// ***** VDMTOOLS END Name=bfDeviation

// ***** VDMTOOLS START Name=integratedDeviation KEEP=NO
  private Number integratedDeviation = null;
// ***** VDMTOOLS END Name=integratedDeviation

// ***** VDMTOOLS START Name=lastMeasurementTime KEEP=NO
  private Number lastMeasurementTime = null;
// ***** VDMTOOLS END Name=lastMeasurementTime


// ***** VDMTOOLS START Name=vdm_init_PIDLightValCtrl KEEP=NO
  private void vdm_init_PIDLightValCtrl () {
    bfDeviation = new Double(0);
    integratedDeviation = new Double(0);
    lastMeasurementTime = new Double(0);
  }
// ***** VDMTOOLS END Name=vdm_init_PIDLightValCtrl


// ***** VDMTOOLS START Name=PIDLightValCtrl KEEP=NO
  public PIDLightValCtrl () /*throws CGException*/ {
    vdm_init_PIDLightValCtrl();
  }
// ***** VDMTOOLS END Name=PIDLightValCtrl


// ***** VDMTOOLS START Name=PIDLightValCtrl#1|PIDLVCParm KEEP=NO
  public PIDLightValCtrl (final PIDLVCParm parm) {
	  vdm_init_PIDLightValCtrl();
	    PIDParm = parm;
	    bfDeviation = new Integer(0);
	    integratedDeviation = new Integer(0);
	    lastMeasurementTime = new Integer(0);
	  //    return new PIDLightValCtrl();
  }
// ***** VDMTOOLS END Name=PIDLightValCtrl#1|PIDLVCParm


//***** VDMTOOLS START Name=reset KEEP=NO
 public void reset () /*throws CGException*/ {
   bfDeviation = new Integer(0);
   integratedDeviation = new Integer(0);
   lastMeasurementTime = new Integer(0);
 }
//***** VDMTOOLS END Name=reset

//***** VDMTOOLS START Name=getCtrlParm KEEP=NO
public PIDLVCParm getCtrlParm () /*throws CGException*/ {
  return PIDParm;
}
//***** VDMTOOLS END Name=getCtrlParm


//***** VDMTOOLS START Name=calcLightValCtrlVal#3|Number|Number|Number KEEP=NO
public Number calcLightValCtrlVal (final Number targLightVal, final Number lightVal, final Number time) /*throws CGException*/ {
 final Number deviation = new Integer(targLightVal.intValue() - lightVal.intValue());
 final Number d_deviation = new Double(bfDeviation.doubleValue() - deviation.intValue());
 integratedDeviation = new Double(integratedDeviation.doubleValue() + (deviation.intValue() * (time.doubleValue() - lastMeasurementTime.doubleValue())));
 bfDeviation = deviation;
 lastMeasurementTime = time;
// return  deviation.doubleValue()* PIDParm.getLKp().doubleValue();

 return (new Double(((deviation.intValue() * PIDParm.getLKp().doubleValue()) + (integratedDeviation.doubleValue() * PIDParm.getLKi().doubleValue())) + (d_deviation.doubleValue() * PIDParm.getLKd().doubleValue()))).intValue();
}


//***** VDMTOOLS START Name=setCtrlParm#1|PIDLVCParm KEEP=NO
public void setCtrlParm (final PIDLVCParm parm) /*throws CGException*/ {
 PIDParm = parm;
}
//***** VDMTOOLS END Name=setCtrlParm#1|PIDLVCParm

}
;
