//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2014-03-10 by the VDM++ to JAVA Code Generator
// (v9.0.3 - Fri 13-Dec-2013 09:24:01 +0900)
//
// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:/Users/HOMMA/Google ?.

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports

public interface WheelMotor {

// ***** VDMTOOLS START Name=rotate#1|Number KEEP=NO
  abstract public void rotate (final Number parm) /*throws CGException*/ ;
// ***** VDMTOOLS END Name=rotate#1|Number


// ***** VDMTOOLS START Name=getRotate KEEP=NO
  abstract public Number getRotate () /*throws CGException*/ ;
// ***** VDMTOOLS END Name=getRotate

}
;
