//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at 2014-03-10 by the VDM++ to JAVA Code Generator
// (v9.0.3 - Fri 13-Dec-2013 09:24:01 +0900)
//
// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// This file was genereted from "C:\\Users\\HOMMA\\Google ?.

// ***** VDMTOOLS START Name=package KEEP=NO
// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=NO
import jp.vdmtools.VDM.UTIL;
import jp.vdmtools.VDM.CGException;
// ***** VDMTOOLS END Name=imports



public class WheelMotorStub implements WheelMotor {

// ***** VDMTOOLS START Name=turn KEEP=NO
  private Number turn = null;
// ***** VDMTOOLS END Name=turn


// ***** VDMTOOLS START Name=vdm_init_WheelMotorStub KEEP=NO
  private void vdm_init_WheelMotorStub () {}
// ***** VDMTOOLS END Name=vdm_init_WheelMotorStub


// ***** VDMTOOLS START Name=WheelMotorStub KEEP=NO
  public WheelMotorStub () throws CGException {
    vdm_init_WheelMotorStub();
    turn = new Integer(0);
  }
// ***** VDMTOOLS END Name=WheelMotorStub


// ***** VDMTOOLS START Name=rotate#1|Number KEEP=NO
  public void rotate (final Number parm) /*throws CGException */{
    turn = parm.intValue();
  }
// ***** VDMTOOLS END Name=rotate#1|Number


// ***** VDMTOOLS START Name=getRotate KEEP=NO
  public Number getRotate () /*throws CGException*/ {
    return turn;
  }
// ***** VDMTOOLS END Name=getRotate

}
;
